<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateAppsCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('apps_countries', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('country_code')->nullable();
            $table->string('country_name')->nullable();
            $table->timestamps();
        });

        $data = [
            [ 'country_code' => 'AF','country_name' => 'Afghanistan'],
            [ 'country_code' => 'AL','country_name' => 'Albania'],
            [ 'country_code' => 'DZ','country_name' => 'Algeria'],
            [ 'country_code' => 'DS','country_name' => 'American Samoa'],
            [ 'country_code' => 'AD','country_name' => 'Andorra'],
            [ 'country_code' => 'AO','country_name' => 'Angola'],
            [ 'country_code' => 'AI','country_name' => 'Anguilla'],
            [ 'country_code' => 'AQ','country_name' => 'Antarctica'],
            [ 'country_code' => 'AG','country_name' => 'Antigua and Barbuda'],
            [ 'country_code' => 'AR','country_name' => 'Argentina'],
            [ 'country_code' => 'AM','country_name' => 'Armenia'],
            [ 'country_code' => 'AW','country_name' => 'Aruba'],
            [ 'country_code' => 'AU','country_name' => 'Australia'],
            [ 'country_code' => 'AT','country_name' => 'Austria'],
            [ 'country_code' => 'AZ','country_name' => 'Azerbaijan'],
            [ 'country_code' => 'BS','country_name' => 'Bahamas'],
            [ 'country_code' => 'BH','country_name' => 'Bahrain'],
            [ 'country_code' => 'BD','country_name' => 'Bangladesh'],
            [ 'country_code' => 'BB','country_name' => 'Barbados'],
            [ 'country_code' => 'BY','country_name' => 'Belarus'],
            [ 'country_code' => 'BE','country_name' => 'Belgium'],
            [ 'country_code' => 'BZ','country_name' => 'Belize'],
            [ 'country_code' => 'BJ','country_name' => 'Benin'],
            [ 'country_code' => 'BM','country_name' => 'Bermuda'],
            [ 'country_code' => 'BT','country_name' => 'Bhutan'],
            [ 'country_code' => 'BO','country_name' => 'Bolivia'],
            [ 'country_code' => 'BA','country_name' => 'Bosnia and Herzegovina'],
            [ 'country_code' => 'BW','country_name' => 'Botswana'],
            [ 'country_code' => 'BV','country_name' => 'Bouvet Island'],
            [ 'country_code' => 'BR','country_name' => 'Brazil'],
            [ 'country_code' => 'IO','country_name' => 'British Indian Ocean Territory'],
            [ 'country_code' => 'BN','country_name' => 'Brunei Darussalam'],
            [ 'country_code' => 'BG','country_name' => 'Bulgaria'],
            [ 'country_code' => 'BF','country_name' => 'Burkina Faso'],
            [ 'country_code' => 'BI','country_name' => 'Burundi'],
            [ 'country_code' => 'KH','country_name' => 'Cambodia'],
            [ 'country_code' => 'CM','country_name' => 'Cameroon'],
            [ 'country_code' => 'CA','country_name' => 'Canada'],
            [ 'country_code' => 'CV','country_name' => 'Cape Verde'],
            [ 'country_code' => 'KY','country_name' => 'Cayman Islands'],
            [ 'country_code' => 'CF','country_name' => 'Central African Republic'],
            [ 'country_code' => 'TD','country_name' => 'Chad'],
            [ 'country_code' => 'CL','country_name' => 'Chile'],
            [ 'country_code' => 'CN','country_name' => 'China'],
            [ 'country_code' => 'CX','country_name' => 'Christmas Island'],
            [ 'country_code' => 'CC','country_name' => 'Cocos (Keeling) Islands'],
            [ 'country_code' => 'CO','country_name' => 'Colombia'],
            [ 'country_code' => 'KM','country_name' => 'Comoros'],
            [ 'country_code' => 'CG','country_name' => 'Congo'],
            [ 'country_code' => 'CK','country_name' => 'Cook Islands'],
            [ 'country_code' => 'CR','country_name' => 'Costa Rica'],
            [ 'country_code' => 'HR','country_name' => 'Croatia (Hrvatska)'],
            [ 'country_code' => 'CU','country_name' => 'Cuba'],
            [ 'country_code' => 'CY','country_name' => 'Cyprus'],
            [ 'country_code' => 'CZ','country_name' => 'Czech Republic'],
            [ 'country_code' => 'DK','country_name' => 'Denmark'],
            [ 'country_code' => 'DJ','country_name' => 'Djibouti'],
            [ 'country_code' => 'DM','country_name' => 'Dominica'],
            [ 'country_code' => 'DO','country_name' => 'Dominican Republic'],
            [ 'country_code' => 'TP','country_name' => 'East Timor'],
            [ 'country_code' => 'EC','country_name' => 'Ecuador'],
            [ 'country_code' => 'EG','country_name' => 'Egypt'],
            [ 'country_code' => 'SV','country_name' => 'El Salvador'],
            [ 'country_code' => 'GQ','country_name' => 'Equatorial Guinea'],
            [ 'country_code' => 'ER','country_name' => 'Eritrea'],
            [ 'country_code' => 'EE','country_name' => 'Estonia'],
            [ 'country_code' => 'ET','country_name' => 'Ethiopia'],
            [ 'country_code' => 'FK','country_name' => 'Falkland Islands (Malvinas)'],
            [ 'country_code' => 'FO','country_name' => 'Faroe Islands'],
            [ 'country_code' => 'FJ','country_name' => 'Fiji'],
            [ 'country_code' => 'FI','country_name' => 'Finland'],
            [ 'country_code' => 'FR','country_name' => 'France'],
            [ 'country_code' => 'FX','country_name' => 'France, Metropolitan'],
            [ 'country_code' => 'GF','country_name' => 'French Guiana'],
            [ 'country_code' => 'PF','country_name' => 'French Polynesia'],
            [ 'country_code' => 'TF','country_name' => 'French Southern Territories'],
            [ 'country_code' => 'GA','country_name' => 'Gabon'],
            [ 'country_code' => 'GM','country_name' => 'Gambia'],
            [ 'country_code' => 'GE','country_name' => 'Georgia'],
            [ 'country_code' => 'DE','country_name' => 'Germany'],
            [ 'country_code' => 'GH','country_name' => 'Ghana'],
            [ 'country_code' => 'GI','country_name' => 'Gibraltar'],
            [ 'country_code' => 'GK','country_name' => 'Guernsey'],
            [ 'country_code' => 'GR','country_name' => 'Greece'],
            [ 'country_code' => 'GL','country_name' => 'Greenland'],
            [ 'country_code' => 'GD','country_name' => 'Grenada'],
            [ 'country_code' => 'GP','country_name' => 'Guadeloupe'],
            [ 'country_code' => 'GU','country_name' => 'Guam'],
            [ 'country_code' => 'GT','country_name' => 'Guatemala'],
            [ 'country_code' => 'GN','country_name' => 'Guinea'],
            [ 'country_code' => 'GW','country_name' => 'Guinea-Bissau'],
            [ 'country_code' => 'GY','country_name' => 'Guyana'],
            [ 'country_code' => 'HT','country_name' => 'Haiti'],
            [ 'country_code' => 'HM','country_name' => 'Heard and Mc Donald Islands'],
            [ 'country_code' => 'HN','country_name' => 'Honduras'],
            [ 'country_code' => 'HK','country_name' => 'Hong Kong'],
            [ 'country_code' => 'HU','country_name' => 'Hungary'],
            [ 'country_code' => 'IS','country_name' => 'Iceland'],
            [ 'country_code' => 'IN','country_name' => 'India'],
            [ 'country_code' => 'IM','country_name' => 'Isle of Man'],
            [ 'country_code' => 'ID','country_name' => 'Indonesia'],
            [ 'country_code' => 'IR','country_name' => 'Iran (Islamic Republic of)'],
            [ 'country_code' => 'IQ','country_name' => 'Iraq'],
            [ 'country_code' => 'IE','country_name' => 'Ireland'],
            [ 'country_code' => 'IL','country_name' => 'Israel'],
            [ 'country_code' => 'IT','country_name' => 'Italy'],
            [ 'country_code' => 'CI','country_name' => 'Ivory Coast'],
            [ 'country_code' => 'JE','country_name' => 'Jersey'],
            [ 'country_code' => 'JM','country_name' => 'Jamaica'],
            [ 'country_code' => 'JP','country_name' => 'Japan'],
            [ 'country_code' => 'JO','country_name' => 'Jordan'],
            [ 'country_code' => 'KZ','country_name' => 'Kazakhstan'],
            [ 'country_code' => 'KE','country_name' => 'Kenya'],
            [ 'country_code' => 'KI','country_name' => 'Kiribati'],
            [ 'country_code' => 'KP','country_name' => 'Korea, Democratic People\'s Republic of'],
            [ 'country_code' => 'KR','country_name' => 'Korea, Republic of'],
            [ 'country_code' => 'XK','country_name' => 'Kosovo'],
            [ 'country_code' => 'KW','country_name' => 'Kuwait'],
            [ 'country_code' => 'KG','country_name' => 'Kyrgyzstan'],
            [ 'country_code' => 'LA','country_name' => 'Lao People\'s Democratic Republic'],
            [ 'country_code' => 'LV','country_name' => 'Latvia'],
            [ 'country_code' => 'LB','country_name' => 'Lebanon'],
            [ 'country_code' => 'LS','country_name' => 'Lesotho'],
            [ 'country_code' => 'LR','country_name' => 'Liberia'],
            [ 'country_code' => 'LY','country_name' => 'Libyan Arab Jamahiriya'],
            [ 'country_code' => 'LI','country_name' => 'Liechtenstein'],
            [ 'country_code' => 'LT','country_name' => 'Lithuania'],
            [ 'country_code' => 'LU','country_name' => 'Luxembourg'],
            [ 'country_code' => 'MO','country_name' => 'Macau'],
            [ 'country_code' => 'MK','country_name' => 'Macedonia'],
            [ 'country_code' => 'MG','country_name' => 'Madagascar'],
            [ 'country_code' => 'MW','country_name' => 'Malawi'],
            [ 'country_code' => 'MY','country_name' => 'Malaysia'],
            [ 'country_code' => 'MV','country_name' => 'Maldives'],
            [ 'country_code' => 'ML','country_name' => 'Mali'],
            [ 'country_code' => 'MT','country_name' => 'Malta'],
            [ 'country_code' => 'MH','country_name' => 'Marshall Islands'],
            [ 'country_code' => 'MQ','country_name' => 'Martinique'],
            [ 'country_code' => 'MR','country_name' => 'Mauritania'],
            [ 'country_code' => 'MU','country_name' => 'Mauritius'],
            [ 'country_code' => 'TY','country_name' => 'Mayotte'],
            [ 'country_code' => 'MX','country_name' => 'Mexico'],
            [ 'country_code' => 'FM','country_name' => 'Micronesia, Federated States of'],
            [ 'country_code' => 'MD','country_name' => 'Moldova, Republic of'],
            [ 'country_code' => 'MC','country_name' => 'Monaco'],
            [ 'country_code' => 'MN','country_name' => 'Mongolia'],
            [ 'country_code' => 'ME','country_name' => 'Montenegro'],
            [ 'country_code' => 'MS','country_name' => 'Montserrat'],
            [ 'country_code' => 'MA','country_name' => 'Morocco'],
            [ 'country_code' => 'MZ','country_name' => 'Mozambique'],
            [ 'country_code' => 'MM','country_name' => 'Myanmar'],
            [ 'country_code' => 'NA','country_name' => 'Namibia'],
            [ 'country_code' => 'NR','country_name' => 'Nauru'],
            [ 'country_code' => 'NP','country_name' => 'Nepal'],
            [ 'country_code' => 'NL','country_name' => 'Netherlands'],
            [ 'country_code' => 'AN','country_name' => 'Netherlands Antilles'],
            [ 'country_code' => 'NC','country_name' => 'New Caledonia'],
            [ 'country_code' => 'NZ','country_name' => 'New Zealand'],
            [ 'country_code' => 'NI','country_name' => 'Nicaragua'],
            [ 'country_code' => 'NE','country_name' => 'Niger'],
            [ 'country_code' => 'NG','country_name' => 'Nigeria'],
            [ 'country_code' => 'NU','country_name' => 'Niue'],
            [ 'country_code' => 'NF','country_name' => 'Norfolk Island'],
            [ 'country_code' => 'MP','country_name' => 'Northern Mariana Islands'],
            [ 'country_code' => 'NO','country_name' => 'Norway'],
            [ 'country_code' => 'OM','country_name' => 'Oman'],
            [ 'country_code' => 'PK','country_name' => 'Pakistan'],
            [ 'country_code' => 'PW','country_name' => 'Palau'],
            [ 'country_code' => 'PS','country_name' => 'Palestine'],
            [ 'country_code' => 'PA','country_name' => 'Panama'],
            [ 'country_code' => 'PG','country_name' => 'Papua New Guinea'],
            [ 'country_code' => 'PY','country_name' => 'Paraguay'],
            [ 'country_code' => 'PE','country_name' => 'Peru'],
            [ 'country_code' => 'PH','country_name' => 'Philippines'],
            [ 'country_code' => 'PN','country_name' => 'Pitcairn'],
            [ 'country_code' => 'PL','country_name' => 'Poland'],
            [ 'country_code' => 'PT','country_name' => 'Portugal'],
            [ 'country_code' => 'PR','country_name' => 'Puerto Rico'],
            [ 'country_code' => 'QA','country_name' => 'Qatar'],
            [ 'country_code' => 'RE','country_name' => 'Reunion'],
            [ 'country_code' => 'RO','country_name' => 'Romania'],
            [ 'country_code' => 'RU','country_name' => 'Russian Federation'],
            [ 'country_code' => 'RW','country_name' => 'Rwanda'],
            [ 'country_code' => 'KN','country_name' => 'Saint Kitts and Nevis'],
            [ 'country_code' => 'LC','country_name' => 'Saint Lucia'],
            [ 'country_code' => 'VC','country_name' => 'Saint Vincent and the Grenadines'],
            [ 'country_code' => 'WS','country_name' => 'Samoa'],
            [ 'country_code' => 'SM','country_name' => 'San Marino'],
            [ 'country_code' => 'ST','country_name' => 'Sao Tome and Principe'],
            [ 'country_code' => 'SA','country_name' => 'Saudi Arabia'],
            [ 'country_code' => 'SN','country_name' => 'Senegal'],
            [ 'country_code' => 'RS','country_name' => 'Serbia'],
            [ 'country_code' => 'SC','country_name' => 'Seychelles'],
            [ 'country_code' => 'SL','country_name' => 'Sierra Leone'],
            [ 'country_code' => 'SG','country_name' => 'Singapore'],
            [ 'country_code' => 'SK','country_name' => 'Slovakia'],
            [ 'country_code' => 'SI','country_name' => 'Slovenia'],
            [ 'country_code' => 'SB','country_name' => 'Solomon Islands'],
            [ 'country_code' => 'SO','country_name' => 'Somalia'],
            [ 'country_code' => 'ZA','country_name' => 'South Africa'],
            [ 'country_code' => 'GS','country_name' => 'South Georgia South Sandwich Islands'],
            [ 'country_code' => 'ES','country_name' => 'Spain'],
            [ 'country_code' => 'LK','country_name' => 'Sri Lanka'],
            [ 'country_code' => 'SH','country_name' => 'St. Helena'],
            [ 'country_code' => 'PM','country_name' => 'St. Pierre and Miquelon'],
            [ 'country_code' => 'SD','country_name' => 'Sudan'],
            [ 'country_code' => 'SR','country_name' => 'Suriname'],
            [ 'country_code' => 'SJ','country_name' => 'Svalbard and Jan Mayen Islands'],
            [ 'country_code' => 'SZ','country_name' => 'Swaziland'],
            [ 'country_code' => 'SE','country_name' => 'Sweden'],
            [ 'country_code' => 'CH','country_name' => 'Switzerland'],
            [ 'country_code' => 'SY','country_name' => 'Syrian Arab Republic'],
            [ 'country_code' => 'TW','country_name' => 'Taiwan'],
            [ 'country_code' => 'TJ','country_name' => 'Tajikistan'],
            [ 'country_code' => 'TZ','country_name' => 'Tanzania, United Republic of'],
            [ 'country_code' => 'TH','country_name' => 'Thailand'],
            [ 'country_code' => 'TG','country_name' => 'Togo'],
            [ 'country_code' => 'TK','country_name' => 'Tokelau'],
            [ 'country_code' => 'TO','country_name' => 'Tonga'],
            [ 'country_code' => 'TT','country_name' => 'Trinidad and Tobago'],
            [ 'country_code' => 'TN','country_name' => 'Tunisia'],
            [ 'country_code' => 'TR','country_name' => 'Turkey'],
            [ 'country_code' => 'TM','country_name' => 'Turkmenistan'],
            [ 'country_code' => 'TC','country_name' => 'Turks and Caicos Islands'],
            [ 'country_code' => 'TV','country_name' => 'Tuvalu'],
            [ 'country_code' => 'UG','country_name' => 'Uganda'],
            [ 'country_code' => 'UA','country_name' => 'Ukraine'],
            [ 'country_code' => 'AE','country_name' => 'United Arab Emirates'],
            [ 'country_code' => 'GB','country_name' => 'United Kingdom'],
            [ 'country_code' => 'US','country_name' => 'United States'],
            [ 'country_code' => 'UM','country_name' => 'United States minor outlying islands'],
            [ 'country_code' => 'UY','country_name' => 'Uruguay'],
            [ 'country_code' => 'UZ','country_name' => 'Uzbekistan'],
            [ 'country_code' => 'VU','country_name' => 'Vanuatu'],
            [ 'country_code' => 'VA','country_name' => 'Vatican City State'],
            [ 'country_code' => 'VE','country_name' => 'Venezuela'],
            [ 'country_code' => 'VN','country_name' => 'Vietnam'],
            [ 'country_code' => 'VG','country_name' => 'Virgin Islands (British)'],
            [ 'country_code' => 'VI','country_name' => 'Virgin Islands (U.S.)'],
            [ 'country_code' => 'WF','country_name' => 'Wallis and Futuna Islands'],
            [ 'country_code' => 'EH','country_name' => 'Western Sahara'],
            [ 'country_code' => 'YE','country_name' => 'Yemen'],
            [ 'country_code' => 'ZR','country_name' => 'Zaire'],
            [ 'country_code' => 'ZM','country_name' => 'Zambia'],
            [ 'country_code' => 'ZW','country_name' => 'Zimbabwe'],
			[ 'country_code' => 'AF','country_name' => 'Афганистан'],
			[ 'country_code' => 'AL','country_name' => 'Албания'],
			[ 'country_code' => 'DZ','country_name' => 'Алжир'],
			[ 'country_code' => 'DS','country_name' => 'американское Самоа'],
			[ 'country_code' => 'AD','country_name' => 'андорра'],
			[ 'country_code' => 'AO','country_name' => 'Ангола'],
			[ 'country_code' => 'AI','country_name' => 'Ангилья'],
			[ 'country_code' => 'AQ','country_name' => 'Антарктида'],
			[ 'country_code' => 'AG','country_name' => 'Антигуа и Барбуда'],
			[ 'country_code' => 'AR','country_name' => 'Аргентина'],
			[ 'country_code' => 'AM','country_name' => 'Армения'],
			[ 'country_code' => 'AW','country_name' => 'Аруба'],
			[ 'country_code' => 'AU','country_name' => 'Австралия'],
			[ 'country_code' => 'AT','country_name' => 'Австрия'],
			[ 'country_code' => 'AZ','country_name' => 'Азербайджан'],
			[ 'country_code' => 'BS','country_name' => 'Багамские о-ва'],
			[ 'country_code' => 'BH','country_name' => 'Бахрейн'],
			[ 'country_code' => 'BD','country_name' => 'Бангладеш'],
			[ 'country_code' => 'BB','country_name' => 'Барбадос'],
			[ 'country_code' => 'BY','country_name' => 'Беларусь'],
			[ 'country_code' => 'BE','country_name' => 'Бельгия'],
			[ 'country_code' => 'BZ','country_name' => 'Белиз'],
			[ 'country_code' => 'BJ','country_name' => 'Бенин'],
			[ 'country_code' => 'BM','country_name' => 'Бермудские острова'],
			[ 'country_code' => 'BT','country_name' => 'Бутан'],
			[ 'country_code' => 'BO','country_name' => 'Боливия'],
			[ 'country_code' => 'BA','country_name' => 'Босния и Герцеговина'],
			[ 'country_code' => 'BW','country_name' => 'Ботсвана'],
			[ 'country_code' => 'BV','country_name' => 'Остров Буве'],
			[ 'country_code' => 'BR','country_name' => 'Бразилия'],
			[ 'country_code' => 'IO','country_name' => 'Британская территория Индийского океана'],
			[ 'country_code' => 'BN','country_name' => 'Бруней-Даруссалам'],
			[ 'country_code' => 'BG','country_name' => 'Болгария'],
			[ 'country_code' => 'BF','country_name' => 'Буркина-Фасо'],
			[ 'country_code' => 'BI','country_name' => 'Бурунди'],
			[ 'country_code' => 'KH','country_name' => 'Камбоджа'],
			[ 'country_code' => 'CM','country_name' => 'Камерун'],
			[ 'country_code' => 'CA','country_name' => 'Канада'],
			[ 'country_code' => 'CV','country_name' => 'Кабо-Верде'],
			[ 'country_code' => 'KY','country_name' => 'Каймановы острова'],
			[ 'country_code' => 'CF','country_name' => 'Центрально-Африканская Республика'],
			[ 'country_code' => 'TD','country_name' => 'Чад'],
			[ 'country_code' => 'CL','country_name' => 'Чили'],
			[ 'country_code' => 'CN','country_name' => 'Китай'],
			[ 'country_code' => 'CX','country_name' => 'Остров Рождества'],
			[ 'country_code' => 'CC','country_name' => 'Кокосовые (Килинг) острова'],
			[ 'country_code' => 'CO','country_name' => 'Колумбия'],
			[ 'country_code' => 'KM','country_name' => 'Коморские острова'],
			[ 'country_code' => 'CG','country_name' => 'Конго'],
			[ 'country_code' => 'CK','country_name' => 'Острова Кука'],
			[ 'country_code' => 'CR','country_name' => 'Коста-Рика'],
			[ 'country_code' => 'HR','country_name' => 'Хорватия (Hrvatska)'],
			[ 'country_code' => 'CU','country_name' => 'Куба'],
			[ 'country_code' => 'CY','country_name' => 'Кипр'],
			[ 'country_code' => 'CZ','country_name' => 'Республика Чехия'],
			[ 'country_code' => 'DK','country_name' => 'Дания'],
			[ 'country_code' => 'DJ','country_name' => 'Джибути'],
			[ 'country_code' => 'DM','country_name' => 'Доминика'],
			[ 'country_code' => 'DO','country_name' => 'Доминиканская Респблика'],
			[ 'country_code' => 'TP','country_name' => 'Восточный Тимор'],
			[ 'country_code' => 'EC','country_name' => 'Эквадор'],
			[ 'country_code' => 'EG','country_name' => 'Египет'],
			[ 'country_code' => 'SV','country_name' => 'Сальвадор'],
			[ 'country_code' => 'GQ','country_name' => 'Экваториальная Гвинея'],
			[ 'country_code' => 'ER','country_name' => 'Эритрея'],
			[ 'country_code' => 'EE','country_name' => 'Эстония'],
			[ 'country_code' => 'ET','country_name' => 'Эфиопия'],
			[ 'country_code' => 'FK','country_name' => 'Фолклендские (Мальвинские)'],
			[ 'country_code' => 'FO','country_name' => 'Фарерские острова'],
			[ 'country_code' => 'FJ','country_name' => 'Фиджи'],
			[ 'country_code' => 'FI','country_name' => 'Финляндия'],
			[ 'country_code' => 'FR','country_name' => 'Франция'],
			[ 'country_code' => 'FX','country_name' => 'Франция, Метрополитен'],
			[ 'country_code' => 'GF','country_name' => 'Французская Гвиана'],
			[ 'country_code' => 'PF','country_name' => 'Французская Полинезия'],
			[ 'country_code' => 'TF','country_name' => 'Южные Французские Территории'],
			[ 'country_code' => 'GA','country_name' => 'Габон'],
			[ 'country_code' => 'GM','country_name' => 'Гамбия'],
			[ 'country_code' => 'GE','country_name' => 'Грузия'],
			[ 'country_code' => 'DE','country_name' => 'Германия'],
			[ 'country_code' => 'GH','country_name' => 'Гана'],
			[ 'country_code' => 'GI','country_name' => 'Гибралтар'],
			[ 'country_code' => 'GK','country_name' => 'шерстяная фуфайка'],
			[ 'country_code' => 'GR','country_name' => 'Греция'],
			[ 'country_code' => 'GL','country_name' => 'Гренландия'],
			[ 'country_code' => 'GD','country_name' => 'Гренада'],
			[ 'country_code' => 'GP','country_name' => 'Гваделупа'],
			[ 'country_code' => 'GU','country_name' => 'Гуам'],
			[ 'country_code' => 'GT','country_name' => 'Гватемала'],
			[ 'country_code' => 'GN','country_name' => 'Гвинея'],
			[ 'country_code' => 'GW','country_name' => 'Гвинея-Бисау'],
			[ 'country_code' => 'GY','country_name' => 'Гайана'],
			[ 'country_code' => 'HT','country_name' => 'Гаити'],
			[ 'country_code' => 'HM','country_name' => 'Слышал и Mc Donald острова'],
			[ 'country_code' => 'HN','country_name' => 'Гондурас'],
			[ 'country_code' => 'HK','country_name' => 'Гонконг'],
			[ 'country_code' => 'HU','country_name' => 'Венгрия'],
			[ 'country_code' => 'IS','country_name' => 'Исландия'],
			[ 'country_code' => 'IN','country_name' => 'Индия'],
			[ 'country_code' => 'IM','country_name' => 'Остров Мэн'],
			[ 'country_code' => 'ID','country_name' => 'Индонезия'],
			[ 'country_code' => 'IR','country_name' => 'Иран (Исламская Республика)'],
			[ 'country_code' => 'IQ','country_name' => 'Ирак'],
			[ 'country_code' => 'IE','country_name' => 'Ирландия'],
			[ 'country_code' => 'IL','country_name' => 'Израиль'],
			[ 'country_code' => 'IT','country_name' => 'Италия'],
			[ 'country_code' => 'CI','country_name' => "Кот-д'Ивуар"],
			[ 'country_code' => 'JE','country_name' => 'Джерси'],
			[ 'country_code' => 'JM','country_name' => 'Ямайка'],
			[ 'country_code' => 'JP','country_name' => 'Япония'],
			[ 'country_code' => 'JO','country_name' => 'Иордания'],
			[ 'country_code' => 'KZ','country_name' => 'Казахстан'],
			[ 'country_code' => 'KE','country_name' => 'Кения'],
			[ 'country_code' => 'KI','country_name' => 'Кирибати'],
			[ 'country_code' => 'KP','country_name' => 'Корея, Корейская Народно-Демократическая Республика'],
			[ 'country_code' => 'KR','country_name' => 'Корея, Республика'],
			[ 'country_code' => 'XK','country_name' => 'Косово'],
			[ 'country_code' => 'KW','country_name' => 'Кувейт'],
			[ 'country_code' => 'KG','country_name' => 'Киргизия'],
			[ 'country_code' => 'LA','country_name' => 'Лаосская Народно-Демократическая Республика'],
			[ 'country_code' => 'LV','country_name' => 'Латвия'],
			[ 'country_code' => 'LB','country_name' => 'Ливан'],
			[ 'country_code' => 'LS','country_name' => 'Лесото'],
			[ 'country_code' => 'LR','country_name' => 'Либерия'],
			[ 'country_code' => 'LY','country_name' => 'Ливийская арабская джамахирия'],
			[ 'country_code' => 'LI','country_name' => 'Лихтенштейн'],
			[ 'country_code' => 'LT','country_name' => 'Литва'],
			[ 'country_code' => 'LU','country_name' => 'Люксембург'],
			[ 'country_code' => 'MO','country_name' => 'Макао'],
			[ 'country_code' => 'MK','country_name' => 'Македония'],
			[ 'country_code' => 'MG','country_name' => 'Мадагаскар'],
			[ 'country_code' => 'MW','country_name' => 'Малави'],
			[ 'country_code' => 'MY','country_name' => 'Малайзия'],
			[ 'country_code' => 'MV','country_name' => 'Мальдивы'],
			[ 'country_code' => 'ML','country_name' => 'Мали'],
			[ 'country_code' => 'MT','country_name' => 'Мальта'],
			[ 'country_code' => 'MH','country_name' => 'Маршалловы острова'],
			[ 'country_code' => 'MQ','country_name' => 'Мартиника'],
			[ 'country_code' => 'MR','country_name' => 'Мавритания'],
			[ 'country_code' => 'MU','country_name' => 'Маврикий'],
			[ 'country_code' => 'TY','country_name' => 'Майотта'],
			[ 'country_code' => 'MX','country_name' => 'Мексика'],
			[ 'country_code' => 'FM','country_name' => 'Микронезия, Федеративные Штаты'],
			[ 'country_code' => 'MD','country_name' => 'Молдова'],
			[ 'country_code' => 'MC','country_name' => 'Монако'],
			[ 'country_code' => 'MN','country_name' => 'Монголия'],
			[ 'country_code' => 'ME','country_name' => 'Черногория'],
			[ 'country_code' => 'MS','country_name' => 'Монсеррат'],
			[ 'country_code' => 'MA','country_name' => 'Марокко'],
			[ 'country_code' => 'MZ','country_name' => 'Мозамбик'],
			[ 'country_code' => 'MM','country_name' => 'Мьянма'],
			[ 'country_code' => 'NA','country_name' => 'Намибия'],
			[ 'country_code' => 'NR','country_name' => 'Науру'],
			[ 'country_code' => 'NP','country_name' => 'Непал'],
			[ 'country_code' => 'NL','country_name' => 'Нидерланды'],
			[ 'country_code' => 'AN','country_name' => 'Нидерландские Антильские острова'],
			[ 'country_code' => 'NC','country_name' => 'Новая Каледония'],
			[ 'country_code' => 'NZ','country_name' => 'Новая Зеландия'],
			[ 'country_code' => 'NI','country_name' => 'Никарагуа'],
			[ 'country_code' => 'NE','country_name' => 'Нигер'],
			[ 'country_code' => 'NG','country_name' => 'Нигерия'],
			[ 'country_code' => 'NU','country_name' => 'Niue'],
			[ 'country_code' => 'NF','country_name' => 'Остров Норфолк'],
			[ 'country_code' => 'MP','country_name' => 'Северные Марианские острова'],
			[ 'country_code' => 'NO','country_name' => 'Норвегия'],
			[ 'country_code' => 'OM','country_name' => 'Оман'],
			[ 'country_code' => 'PK','country_name' => 'Пакистан'],
			[ 'country_code' => 'PW','country_name' => 'Palau'],
			[ 'country_code' => 'PS','country_name' => 'Палестина'],
			[ 'country_code' => 'PA','country_name' => 'Панама'],
			[ 'country_code' => 'PG','country_name' => 'Папуа - Новая Гвинея'],
			[ 'country_code' => 'PY','country_name' => 'Парагвай'],
			[ 'country_code' => 'PE','country_name' => 'Перу'],
			[ 'country_code' => 'PH','country_name' => 'Филиппины'],
			[ 'country_code' => 'PN','country_name' => 'Питкэрн'],
			[ 'country_code' => 'PL','country_name' => 'Польша'],
			[ 'country_code' => 'PT','country_name' => 'Португалия'],
			[ 'country_code' => 'PR','country_name' => 'Пуэрто-Рико'],
			[ 'country_code' => 'QA','country_name' => 'Катар'],
			[ 'country_code' => 'RE','country_name' => 'воссоединение'],
			[ 'country_code' => 'RO','country_name' => 'Румыния'],
			[ 'country_code' => 'RU','country_name' => 'Российская Федерация'],
			[ 'country_code' => 'RW','country_name' => 'Руанда'],
			[ 'country_code' => 'KN','country_name' => 'Сент-Китс и Невис'],
			[ 'country_code' => 'LC','country_name' => 'Сент-Люсия'],
			[ 'country_code' => 'VC','country_name' => 'Святой Винсент и Гренадины'],
			[ 'country_code' => 'WS','country_name' => 'Самоа'],
			[ 'country_code' => 'SM','country_name' => 'Сан - Марино'],
			[ 'country_code' => 'ST','country_name' => 'Сан-Томе и Принсипи'],
			[ 'country_code' => 'SA','country_name' => 'Саудовская Аравия'],
			[ 'country_code' => 'SN','country_name' => 'Сенегал'],
			[ 'country_code' => 'RS','country_name' => 'Сербия'],
			[ 'country_code' => 'SC','country_name' => 'Сейшельские острова'],
			[ 'country_code' => 'SL','country_name' => 'Сьерра-Леоне'],
			[ 'country_code' => 'SG','country_name' => 'Сингапур'],
			[ 'country_code' => 'SK','country_name' => 'Словакия'],
			[ 'country_code' => 'SI','country_name' => 'Словения'],
			[ 'country_code' => 'SB','country_name' => 'Соломоновы острова'],
			[ 'country_code' => 'SO','country_name' => 'Сомали'],
			[ 'country_code' => 'ZA','country_name' => 'Южная Африка'],
			[ 'country_code' => 'GS','country_name' => 'Сандвичевы острова Южная Джорджия Южная'],
			[ 'country_code' => 'ES','country_name' => 'Испания'],
			[ 'country_code' => 'LK','country_name' => 'Шри Ланка'],
			[ 'country_code' => 'SH','country_name' => 'Святой Елены'],
			[ 'country_code' => 'PM','country_name' => 'Сен-Пьер и Микелон'],
			[ 'country_code' => 'SD','country_name' => 'Судан'],
			[ 'country_code' => 'SR','country_name' => 'Суринам'],
			[ 'country_code' => 'SJ','country_name' => 'Шпицберген и Ян-Майен'],
			[ 'country_code' => 'SZ','country_name' => 'Свазиленд'],
			[ 'country_code' => 'SE','country_name' => 'Швеция'],
			[ 'country_code' => 'CH','country_name' => 'Швейцария'],
			[ 'country_code' => 'SY','country_name' => 'Сирийская Арабская Республика'],
			[ 'country_code' => 'TW','country_name' => 'Тайвань'],
			[ 'country_code' => 'TJ','country_name' => 'Таджикистан'],
			[ 'country_code' => 'TZ','country_name' => 'Танзания, Объединенная Республика'],
			[ 'country_code' => 'TH','country_name' => 'Таиланд'],
			[ 'country_code' => 'TG','country_name' => 'Идти'],
			[ 'country_code' => 'TK','country_name' => 'Токелау'],
			[ 'country_code' => 'TO','country_name' => 'Тонга'],
			[ 'country_code' => 'TT','country_name' => 'Тринидад и Тобаго'],
			[ 'country_code' => 'TN','country_name' => 'Тунис'],
			[ 'country_code' => 'TR','country_name' => 'Турция'],
			[ 'country_code' => 'TM','country_name' => 'Туркменистан'],
			[ 'country_code' => 'TC','country_name' => 'Теркс и Кайкос'],
			[ 'country_code' => 'TV','country_name' => 'Тувалу'],
			[ 'country_code' => 'UG','country_name' => 'Уганда'],
			[ 'country_code' => 'UA','country_name' => 'Украина'],
			[ 'country_code' => 'AE','country_name' => 'Объединенные Арабские Эмираты'],
			[ 'country_code' => 'GB','country_name' => 'объединенное Королевство'],
			[ 'country_code' => 'US','country_name' => 'Соединенные Штаты'],
			[ 'country_code' => 'UM','country_name' => 'США Внешние малые острова'],
			[ 'country_code' => 'UY','country_name' => 'Уругвай'],
			[ 'country_code' => 'UZ','country_name' => 'Узбекистан'],
			[ 'country_code' => 'VU','country_name' => 'Вануату'],
			[ 'country_code' => 'VA','country_name' => 'Государство Ватикан'],
			[ 'country_code' => 'VE','country_name' => 'Венесуэла'],
			[ 'country_code' => 'VN','country_name' => 'Вьетнам'],
			[ 'country_code' => 'VG','country_name' => 'Виргинские острова (Британские)'],
			[ 'country_code' => 'VI','country_name' => 'Виргинские острова (США)'],
			[ 'country_code' => 'WF','country_name' => 'Уоллис и Футуна острова'],
			[ 'country_code' => 'EH','country_name' => 'Западная Сахара'],
			[ 'country_code' => 'YE','country_name' => 'Йемен'],
			[ 'country_code' => 'ZR','country_name' => 'Заир'],
			[ 'country_code' => 'ZM','country_name' => 'Замбия'],
			[ 'country_code' => 'ZW','country_name' => 'Зимбабве'],
			
			
        ];

        // Insert some stuff
        DB::table('apps_countries')->insert( $data );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('apps_countries');
    }
}